# 판다스란?
- 차트 그리기용
- 다양한 타입의 데이터를 표로 다루는 애
- 표 또는 차트 그릴 수 있도록 도와줌
- 벡터라이제이션 vectorization (리스트로 데이터를 가진 일차원 프레임 구조)

In [1]:
import pandas as pd

In [ ]:
df_simple = pd.DataFrame({
    "과일": ["사과", "바나나", "딸기", "포도"],
    "가격": [1500, 800, 2000, 3500],
    "수량": [10, 25, 15, 8],
})

df_simple

    과일    가격  수량
0   사과  1500  10
1  바나나   800  25
2   딸기  2000  15
3   포도  3500   8

In [4]:
df_simple.describe() #기술통계

                가격         수량
count     4.000000   4.000000
mean   1950.000000  14.500000
std    1144.552314   7.593857
min     800.000000   8.000000
25%    1325.000000   9.500000
50%    1750.000000  12.500000
75%    2375.000000  17.500000
max    3500.000000  25.000000

In [ ]:
#원하는 컬럼만 뽑아낼 수 있다

df_simple["가격"] #시리즈 꺼내는 것

0    1500
1     800
2    2000
3    3500
Name: 가격, dtype: int64

In [ ]:
# 타입 변경 가능
df_simple["가격"].astype(str)

0    1500
1     800
2    2000
3    3500
Name: 가격, dtype: str

In [ ]:
df_simple.info()  # 위 타입 변경은 복사본에 한것이라 원본은 타입변경 되지않음

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   과일      4 non-null      str
 1   가격      4 non-null      int64
 2   수량      4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 255.0 bytes

In [ ]:
df_simple["가격"] = df_simple["가격"].astype(str) # 이렇게 원본에 넣어줘야 타입 변경 완료

df_simple.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   과일      4 non-null      str
 1   가격      4 non-null      str
 2   수량      4 non-null      int64
dtypes: int64(1), str(2)
memory usage: 270.0 bytes

In [13]:
# 리스트로 시리즈 생성
data = [1, 2, 3, 4, 5]
s1 = pd.Series(data) # s1 이 시리즈
print(s1)

type(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

pandas.Series

In [16]:
# 인덱스 지정하여 시리즈 생성
data = [1, 2, 3, 4, 5]
s_name = ['a', 'b', 'c', 'd', 'e']
s2 = pd.Series(data, index=s_name)
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [15]:
# 딕셔너리로 시리즈 생성 - 키가 인덱스가 됨
dict_data = {'a':1, 'b':2, 'c':3, 'd':4}
s3 = pd.Series(dict_data)
print(s3)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
# location - 판다시의 시리즈인걸 한눈에 알아볼 수 있어서 이롷게 쓰는걸 선호한다
# 인덱스명을 사용한다
# 라벨 인데스
s3.loc['a']

np.int64(1)

In [ ]:
#index의 loc, 자동생성 index 숫자를 사용한다
#위치 인덱싱 - 항상 0으로 시작함
s3.iloc['a']

In [21]:
population = pd.Series([9776, 2729, 1566, 3158], 
                    index=['서울', '부산', '인천', '대구'])

print(population['서울'])  # 9776 출력
print(population[['서울', '부산']])  # 서울과 부산의 데이터만 선택

9776
서울    9776
부산    2729
dtype: int64

In [ ]:
print(population['인천'])
print(population.loc['인천'])
print(population.iloc[2])

1566
1566
1566

# 데이터프레임 DataFrame
다스에서 가장 많이 사용되는 2차원 데이터 구조로, 행과 열로 구성된 표 형태의 데이터를 저장하고 처리하는데 최적화

# 2. Numpy
- '숫자만' 다룸